FROM    ft-rails:on-build

EXPOSE  3000
CMD     ["rails", "s", "-b", "0.0.0.0", "-p", "3000"]

# How to build it?
# docker build -t ex02 .

# How to run it?
# docker run -it --rm -p 8080:3000 ex02

#But firstly you should to go to ft_rails and there built your Dockerfile, next you should to leave and build you main Dockerfile, next run it 
# go to browser and write your (docker-machine ip) docker-machine ip Char :8080
# app on the link https://github.com/dsandshr/docker-1/tree/master/01_dockerfile/ex02/app
